name: Tateyama-Install-Dependencies

inputs:
  checkout:
    description: Skip checkout if false
    default: true
  path:
    description: Relative path under $GITHUB_WORKSPACE to place the repository
    default: build-deps
  sharksfin_implementation:
    description: switch sharksfin implementation
    default: shirakami
  cmake_build_option:
    type: string
    default: ''

runs:
  using: "composite"

  steps:
    - name: Checkout_Takatori
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}
      with:
        repository: project-tsurugi/takatori
        path: ${{ inputs.path }}/takatori
        ref: master

    - name: Checkout_Limestone
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}
      with:
        repository: project-tsurugi/limestone
        path: ${{ inputs.path }}/limestone
        ref: dist-tx-bench-2026

    - name: Checkout_Yakushima
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' && inputs.sharksfin_implementation == 'shirakami' }}

      with:
        repository: project-tsurugi/yakushima
        path: ${{ inputs.path }}/yakushima
        ref: master

    - name: Checkout_Shirakami
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' && inputs.sharksfin_implementation == 'shirakami' }}
      with:
        repository: project-tsurugi/shirakami
        path: ${{ inputs.path }}/shirakami
        ref: dist-tx-bench-2026

    - name: Checkout_Sharksfin
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}
      with:
        repository: project-tsurugi/sharksfin
        path: ${{ inputs.path }}/sharksfin
        ref: master

    - name: Checkout_Data_Relay_gRPC
      uses: actions/checkout@v4
      if: ${{ inputs.checkout == 'true' }}
      with:
        repository: project-tsurugi/data-relay-grpc
        path: ${{ inputs.path }}/data-relay-grpc
        ref: 3981dab124d2bcb61ba69e8a4fbefe55fdab387d

    - name: Install_Takatori
      run: |
        cd ${{ inputs.path }}/takatori
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_Limestone
      run: |
        cd ${{ inputs.path }}/limestone
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_Yakushima
      if: ${{ inputs.sharksfin_implementation == 'shirakami' }}
      run: |
        cd ${{ inputs.path }}/yakushima
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_BENCHMARK=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_Shirakami
      if: ${{ inputs.sharksfin_implementation == 'shirakami' }}
      run: |
        cd ${{ inputs.path }}/shirakami
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_BENCHMARK=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_Sharksfin
      run: |
        if [[ "${{ inputs.sharksfin_implementation }}" == "memory" ]]; then
          _OPTS="-DBUILD_MEMORY=ON -DBUILD_SHIRAKAMI=OFF"
        fi

        cd ${{ inputs.path }}/sharksfin
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${_OPTS} ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_moodycamel_Concurrentqueue
      run: |
        cd third_party/concurrentqueue
        rm -fr build_debug
        mkdir build_debug
        cd build_debug
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash

    - name: Install_Data_Relay_gRPC
      run: |
        cd ${{ inputs.path }}/data-relay-grpc/server
        rm -fr build
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBUILD_TESTS=OFF -DBUILD_DOCUMENTS=OFF -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ${{ inputs.cmake_build_option }} ..
        cmake --build . --target install --clean-first
      shell: bash
